project:
  type: website
  output-dir: docs

website:
  page-footer: "Copyright 2024, Felix Lennert ([felix.lennert@uni-leipzig.de](mailto:felix.lennert@uni-leipzig.de))" 
  title: "Toolbox CSS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Lectures
        menu:
          - href: lectures-overview.qmd
          - href: week_1.qmd
          - href: week_2.qmd
      - text: R Script
        menu: 
          - href: 1_r_index.qmd
          - href: 2_r_catch-up.qmd
          - href: 3_stringr_regex.qmd
          - href: 4_crawling.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



